let User,CustomErrorHandler;_29c‍.x([["default",()=>_29c‍.o]]);_29c‍.w("../models/user",[["default",["User"],function(v){User=v}]]);_29c‍.w("../services/CustomeErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const admin = async (req, res, next) => {
  try {
    const user = await User.findOne({ _id: req.user._id });
    if (user.role === "admin") {
      // console.log("inside try of  admin.js");
      next();
    } else {
      return next(CustomErrorHandler.unAuthorize());
    }
  } catch (error) {
    console.log("inside admin.js");
    return next(CustomErrorHandler.serverError());
  }
};

_29c‍.d(admin);
